### ISSUE TITLE
Checklist for v1.0

### ISSUE THREAD

**Issue by sheridanchris** [sheridanchris/bulletin#9]
Checklist:
- [ ] #6 
- [x] Client-side validation logic
- [ ] Feed deletion
- [ ] Edit subscribed feed name
- [ ] Improve mobile UI
- [ ] Assess and improve accessibility
- [ ] Get app ready for production
